# permissions for end users to view renderers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: renderer-viewer-role
rules:
- apiGroups:
  - tpl2git.stephanhcb.github.io
  resources:
  - renderers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tpl2git.stephanhcb.github.io
  resources:
  - renderers/status
  verbs:
  - get
