
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tpl2git.stephanhcb.github.io
  resources:
  - renderers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tpl2git.stephanhcb.github.io
  resources:
  - renderers/finalizers
  verbs:
  - update
- apiGroups:
  - tpl2git.stephanhcb.github.io
  resources:
  - renderers/status
  verbs:
  - get
  - patch
  - update
